services:
  user-service:
    build: ./User-Service
    ports:
      - "9090:9090"
    env_file:
      - ./User-Service/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: on-failure
    networks:
      - user_file
      - user_data
      - auth
      - redis_caching
      - proxy

  auth-service:
      build: ./Auth-Service
      ports:
        - "9091:9090"
      env_file:
        - ./Auth-Service/.env
      networks:
        - auth
        - proxy

  file-serving:
    build: ./FileServing
    ports:
      - "9092:9090"
    volumes:
      - ./SharedAssets/uploads:/app/uploads
    networks:
      - user_file
      - proxy

  file-service:
    build: ./File-Service
    ports:
      - "9093:9090"
    volumes:
      - ./SharedAssets/uploads:/app/uploads
    networks:
      - user_file
      - proxy


  nginx:
    build: ./nginx
    ports:
      - "443:443"
    env_file:
      - ./nginx/.nginx.env
    volumes:
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      user-service:
        condition: service_started
      auth-service:
        condition: service_started
    networks:
      - proxy

  postgres:
    image: postgres:15
    ports:
      - "5431:5432"
    env_file:
      - ./User-Service/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - user_data

#  mongo:
#    image: mongo:latest
#    ports:
#      - "27018:27017"
#    volumes:
#      - mongo-data:/mongodb/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - redis_caching
      - proxy

volumes:
  postgres-data:
  mongo-data:
  redis-data:

networks:
  proxy:
    driver: bridge
  auth:
    driver: bridge
  user_file:
    driver: bridge
  redis_caching:
    driver: bridge
  user_data:
    driver: bridge
  chat:
    driver: bridge